### ISSUE TITLE
Include and override order

### ISSUE THREAD

**Issue by mindojo-victor** [circus-tent/circus#1014]
I looking to switch to Circus from Supervisor. I want to have a kind of local settings for circus. Something like:
```ini
[circus]
include = circus/app.ini
include = circus/local.ini

circus/app.ini
[watcher:app]
cmd =  ...
autostart = true
numprocesses = 4

circus/local.ini
[watcher:app]
autostart = false
numprocesses = 2
```
`circus/local.ini` would contain overridden settings. Several questions:
1. What will happen if `circus/local.ini` is not present? Failure?
2. If I will use `include = circus/*.ini` -- what is the order of inclusion? Sorted by file name? Is this guarantied?
3. How can I ensure that `local.ini` is included last, so it's overridden values are applied? And will this work at all to define same section`[watcher:app]` with some changed settings?

**Comment by k4nar** [comment]
> What will happen if circus/local.ini is not present? Failure?

This will not fail but log a warning:
```
WARNING:circus:"'circus/local.ini'" does not lead to any config. Make sure include paths are relative to the main config file
```

> If I will use include = circus/*.ini -- what is the order of inclusion? Sorted by file name? Is this guarantied?

No, the order is not guaranteed and should be the same than the ordering on the filesystem (I think this what `ls -U` outputs).

> How can I ensure that local.ini is included last, so it's overridden values are applied? And will this work at all to define same section[watcher:app] with some changed settings?

I don't think the includes actually override anything. I think that's append only, but it's to be confirmed.
