### ISSUE TITLE
`numprocesses` dependent on number of CPU cores

### ISSUE THREAD

**Issue by mindojo-victor** [circus-tent/circus#1020]
I have in my `circus.ini`:
```ini
[watcher:appp]
cmd = ...
numprocesses = 4
```

How can a make `numprocesses` equal to number of CPU cores or calculated?

**Comment by k4nar** [comment]
You could pass that as an env variable maybe ?

**Comment by mindojo-victor** [comment]
Is this much different than just changing the `ini` file?

**Comment by k4nar** [comment]
Well I don't know your requirements :) . If you know the number of processes, then you can just put it in the `.ini`. If you want to run the same ini on several machines then an env variable should do the trick.

**Comment by mindojo-victor** [comment]
My Gunicorn config looked (before it got replaced by Circus) like this:
```python
import multiprocessing
...

    'workers': multiprocessing.cpu_count() * 2,
   ...
```
I'd like to have the same approach in Circus.
