### ISSUE TITLE
Multiple `Circusd`s on the same machine

### ISSUE THREAD

**Issue by mindojo-victor** [circus-tent/circus#1021]
My `circus.ini`:
```ini
[circus]
logoutput = run/circus.log
pidfile = run/circus.pid
# use sock files, not TCP ports -- to allow multiple `circusd`s on the same machine
endpoint = ipc://run/circus.sock
pubsub_endpoint = ipc://run/circus-pubsub.sock

...
```
The application is running, but `circusctl` is not working
```
$ circusctl status
Timed out.
A time out usually happens in one of those cases:

#1 The Circus daemon could not be reached.
#2 The Circus daemon took too long to perform the operation

For #1, make sure you are hitting the right place
by checking your --endpoint option.

For #2, if you are not expecting a result to
come back, increase your timeout option value
(particularly with waiting switches)
```
or
```
$ circusctl --endpoint run/circus.sock status
Traceback (most recent call last):
  File ".../bin/circusctl", line 11, in <module>
    sys.exit(main())
  File ".../lib/python3.5/site-packages/circus/circusctl.py", line 400, in main
    ssh_keyfile=globalopts['ssh_keyfile'])
  File ".../lib/python3.5/site-packages/circus/client.py", line 97, in __init__
    get_connection(self.socket, endpoint, ssh_server, ssh_keyfile)
  File ".../lib/python3.5/site-packages/circus/util.py", line 841, in get_connection
    socket.connect(endpoint)
  File "zmq/backend/cython/socket.pyx", line 528, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:5971)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
zmq.error.ZMQError: Invalid argument
```

**Comment by k4nar** [comment]
I think you have to use `circusctl --endpoint icp://run/circus.sock status`.

**Comment by mindojo-victor** [comment]
I am getting:
```
zmq.error.ZMQError: Protocol not supported
```
Anyway, why `circusctl status` doesn't work taking the endpoint from the config file? Because of this error?

**Comment by k4nar** [comment]
I made a typo, it's `ipc` and not `icp` :) .

> Anyway, why circusctl status doesn't work taking the endpoint from the config file? 

circusctl isn't aware of the config file. You can run circusctl from another directory or even another computer in some cases.

**Comment by mindojo-victor** [comment]
Yes, that works! Sorry for no rechecking you suggestion. I hanged it the end (which happens often), I use like others suggest `python -m circus.circusctl --endpoint ipc://run/circus.sock status`

>circusctl isn't aware of the config file. 

This differs from supervisor. I had in my `supervisord.conf`:
```ini
[unix_http_server]
file = %(here)s/run/supervisord.sock   ; (the path to the socket file)

[supervisorctl]
serverurl = unix://%(here)s/run/supervisord.sock ; use a unix:// URL  for a unix socket
```
and it works without other moves.

**Comment by mindojo-victor** [comment]
> circusctl isn't aware of the config file.

I would really handy to be able to pass config file to `circusctl`, instead of to passing him `--endpoint`, which is dependent on the project.

I guess `circusd` not discovering `circus.ini` in the current folder or some other predetermined location is intentional, but is the motivation behind it?

**Comment by k4nar** [comment]
`circusd` config file doesn't really make sense for `circusctl`. Giving the config file to `circusctl` only for the endpoint seems a bit overkill and confusing to me.

You should see `circusctl` a controller for any circusd daemon.

**Comment by mindojo-victor** [comment]
I see. I think we'll stay with Supervisor.

**Comment by k4nar** [comment]
Ok, no problem :) .

If I may, you should look into systemd, I think it's ready to supersede supervisor and circus.

**Comment by mindojo-victor** [comment]
I will look at Systemd when I find a comprehensible article with use cases and examples. Thanks
