### ISSUE TITLE
ThreadedArbiter invokes Thread._stop() instead of Arbiter._stop()

### ISSUE THREAD

**Issue by prokher** [circus-tent/circus#1025]
`ThreadedArbiter` class inherits from both `Thread` and `Arbiter`.
When method `ThreadedArbiter.stop()` called it invokes `Arbiter.stop()` which in turn calls `self._stop(True)`. Unfortunately, with such inheritance scheme the latter is the method of `threading.Thread`. And process hangs forever on `self.join()` in `ThreadedArbiter.stop`. It looks like multiple inheritance from both `Arbiter` and `Thread` is not a good idea. Probably it is better to encapsulate the instance of `Thread` to avoid such name clashes.

**Comment by k4nar** [comment]
Nice catch!

I think I would accept a patch encapsulating the thread if it came with a lot of tests :) . But it might actually be easier to just fix this by overloading `ThreadedArbiter.stop`.

**Comment by biozz** [comment]
This has been fixed in 29b0bf3d99778875a2151143428e81f89f229cc0

**Comment by k4nar** [comment]
Thanks for the heads up!
