### ISSUE TITLE
Unicode config variables are not expanded

### ISSUE THREAD

**Issue by jferguson-gnubio** [circus-tent/circus#1034]
If the configuration file variables are unicode, `get_config._expand_vars()` fails to expand them because `isinstance(target[key], str)` evaluates to False.  It seems to work ok with the check `isinstance(target[key], basestring)`, which I think is what the test should be.

**Comment by k4nar** [comment]
Indeed, we should use `six.string_types` for that. I'll make a quick PR!

**Comment by k4nar** [comment]
Fixed in https://github.com/circus-tent/circus/pull/1035.

**Comment by jferguson-gnubio** [comment]
awesome, thanks.
