### ISSUE TITLE
Sort plugin config string to fix stalled builds and prevent unnecessary worker restarts

### ISSUE THREAD

**Issue by asterite3** [circus-tent/circus#1038]
If I'm not mistaken, builds get stalled because there is some process spawned by the tests that continues running endlessly after test code finishes. Travis CI probably uses some kind of process grouping that detects that a process created by the tests still exists, so it thinks tests are not finished, and, after 10 minutes it reports that tests failed with a timeout.

After running the tests several times myself, I found that indeed sometimes there is a process left running forever after the tests finished.
```shell
# tox
GLOB sdist-make: /root/circus-own/circus/setup.py
...
Build finished. The HTML pages are in build/html.
make: Leaving directory '/root/circus-own/circus/docs'
_________________ summary ______________...
  py26: commands succeeded
  py26-no-gevent: commands succeeded
  py27: commands succeeded
  py27-no-gevent: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  flake8: commands succeeded
  docs: commands succeeded
  congratulations :)
# ps aux|cat
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18352  3096 ?        Ss+  Apr30   0:00 /bin/bash
root     16093  0.3  0.2 195472 23832 ?        Ssl  12:22   0:00 /root/circus-own/circus/.tox/py34/bin/python3.4 -c from circus import plugins;plugins.main() --endpoint tcp://127.0.0.1:7555 --pubsub tcp://127.0.0.1:7556 --config watcher:test1:::__name__:plugin:myplugin:::name:plugin:myplugin circus.plugins.resource_watcher.ResourceWatcher
```
This process with plugin `watcher:test1:::__name__:plugin:myplugin:::name:plugin:myplugin` keeps running forever. I think this is the reason build gets stalled and killed with a timeout. Actually, this can be seen from the logs - during builds that timeouted circus reports that it started a plugin running `circus.tests.test_reloadconfig` (for example, see https://travis-ci.org/circus-tent/circus/jobs/217126760#L392 or https://travis-ci.org/circus-tent/circus/jobs/221154598#L390):
```test_reload_envdictparsed (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_ignorearbiterwatchers (circus.tests.test_reloadconfig.TestConfig) ... ok
test_reload_numprocesses (circus.tests.test_reloadconfig.TestConfig) ... ok
test_watcher_names (circus.tests.test_reloadconfig.TestConfig) ... ok
test_dummy (circus.tests.test_runner.TestRunner) ... 2017-03-31 11:00:55 circus[4831] [INFO] Loading the plugin...
2017-03-31 11:00:55 circus[4831] [INFO] Endpoint: 'tcp://127.0.0.1:7555'
2017-03-31 11:00:55 circus[4831] [INFO] Pub/sub: 'tcp://127.0.0.1:7556'
2017-03-31 11:00:55 circus[4831] [INFO] Starting
ok
```
While logs for builds that did not fail do not have such record.

The reason this plugin is started is that Arbiter thinks this plugin's command is changed when config is reloaded. It happens in a call to `reload_from_config()`, here: https://github.com/circus-tent/circus/blob/master/circus/arbiter.py#L417.
```python
            # ...
            new_watcher_cfg = (self.get_watcher_config(new_cfg, n) or
                               self.get_plugin_config(new_cfg, n))
            old_watcher_cfg = w._cfg.copy()
            # ...
            diff = DictDiffer(new_watcher_cfg, old_watcher_cfg).changed()
            # ...
            if diff == set(['numprocesses']): # diff is a set {'cmd'} here
                # if nothing but the number of processes is
                # changed, just changes this
                w.set_numprocesses(int(new_watcher_cfg['numprocesses']))
                changed = False
            else:
                changed = len(diff) > 0

            if changed: # changed is True
                # Others things are changed. Just delete and add the watcher.
                changed_wn.add(n)
                deleted_wn.add(n)
                added_wn.add(n)
            # ...
            for n in added_wn:
            # ...
            yield self.start_watcher(w)
            # ...
```

The command looks like this: `/root/circus-own/circus/.tox/py34/bin/python3.4 -c from circus import plugins;plugins.main() --endpoint tcp://127.0.0.1:7555 --pubsub tcp://127.0.0.1:7556 --config watcher:test1:::__name__:plugin:myplugin:::name:plugin:myplugin circus.plugins.resource_watcher.ResourceWatcher`. The reason it is considered changed is that `--config <CONFIG>` portion changes. Sometimes `<CONFIG>` looks like this:
```
name:plugin:myplugin:::__name__:plugin:myplugin:::watcher:test1
```
And sometimes it can look like this:
```
watcher:test1:::__name__:plugin:myplugin:::name:plugin:myplugin
```
These strings correspond to the same config, but the order of key:value pairs is different, so config strings and hence commands are treated unequal.

Plugin config is converted to string in `plugins/__init__.py`:
```python
def _cfg2str(cfg):
    return ':::'.join(['%s:%s' % (key, val) for key, val in cfg.items()])
```
It makes a list of key:value pairs in the dict and joins them. The problem is that dicts are unordered, so the order of elements can be arbitrary and may be different even for dicts with the same set of key:value pairs.
I suggest to sort key:value pairs before joining them to string: https://github.com/asterite3/circus/commit/08d143a4b997c51056c75cdcf96a31a769995c32 (I can make a pull request from that).
This should fix the tests and also prevent unnesessary restarts of plugins when arbiter's config is reloaded, but plugin's config is not really changed.

Another way to fix tests would be to ensure that no processes spawned by a test are left running after the test is done.

**Comment by k4nar** [comment]
Indeed, this makes perfect sense. I would be very interested in a PR with your fix.
