### ISSUE TITLE
Why the session can not be shared in two processes

### ISSUE THREAD

**Issue by moskiGithub** [circus-tent/circus#1043]
I use circus create an application,and set numprocesses=2.When startup it,I found the session can not be shared. How to solve it??? 
The serve.ini:
[circus]
check_delay =5
endpoint = tcp://127.0.0.1:5555
pubsub_enpoint = tcp://127.0.0.1:5556
stats_endpoint = tcp://127.0.0.1:5557

[watcher:webworker]
cmd = /usr/local/hpcc/env/bin/chaussette --fd $(circus.sockets.webapp) wsgi.application
use_sockets = True
numprocesses = 2

[socket:webapp]
host = 127.0.0.1
port = 6543

**Comment by zogzog** [comment]
In-memory session sharing cannot work with processes. You need a persistent session manager within your web app to handle this situation.

**Comment by biozz** [comment]
Agreed with @zogzog. 

@moskiGithub I am sorry, but this is indeed a non-circus issue. I would advise you to search for "communication between processes" or "server-side session storage" to solve this issue. There is plenty of information out there.
