### ISSUE TITLE
Python API to a circusd instance

### ISSUE THREAD

**Issue by stefanocrosta** [circus-tent/circus#1047]
Hello! 
Following #1046 we have started exploring more in detail using Circus for our needs, and we are now at a big crossroad.

We are interested into the Python API approach, even thou in #981 you write:

> May I ask why you're not using a configuration file and circusd (like all the examples in the doc) ? Circus can be used via the Python API, but it's definitively not the recommended way (and it's badly documented).

But the python API /is/ what interests us, because we dynamically create (destroy, re-launch) processes)

We have multiple endpoints that might want to spawn a new process. With the current Circus python approach, each endpoint will have to create its own `circusd` via the `arbiter` class.

We would prefer, instead, to have a single circusd instance running (and started by initd/systemd) and multiple python endpoint being able to create their watchers on that instance.

If I'm not mistaken, this is not currently supported by the existing API.
We would need some kind of ArbiterProxy that speaks via 0MQ to the circusd default daemon (a bit like circusctl does).
The biggest obstacle we foresee is how to implement the Hooks in this case (there should be some messaging with a corresponding blocking state - and maybe a timeout - in the daemon).

Is this something you have been pondering, that you consider doable/interesting for the project?
any feedback would be useful,

Thanks!

**Comment by k4nar** [comment]
If you create on Arbiter instance, you can access its 0MQ socket from any process. Via this socket you can send commands to manager your watchers.
All the commands are listed here: https://github.com/circus-tent/circus/tree/master/circus/commands

Wouldn't that suit your need?

**Comment by stefanocrosta** [comment]
Hello Yannick,
yes of course, but we were missing a nice python api to do that, as well as an official answer if that's a proper way of doing it. 
So we went ahead and implemented it - basically the symmetric of the listening commands that you point at. Is this something you deem interesting to bring into circus?

Basically in our current architecture circusd will be launched by initd/systemd; it will have in its config to spawn our main management python process that will, in turn, launch some other processes based on some more dynamic config; afterwards, another python process might want to manage its own processes and it has the choice to use the main circusd, through 0mq, or create its own new arbiter.

Hope this makes sense and it's not too much of a stretch!

**Comment by k4nar** [comment]
Yes I think it makes sense. And no, I don't think we really need a library for that in Circus. A third party already exists, although I don't know if it's used: https://github.com/msempere/easy_circus

**Comment by stefanocrosta** [comment]
Thanks for your feedback!
Ahah, we did not find easy_circus, thanks for the pointer!
We basically did the same on our own - BUT, asyncio-based (by the way, that requires the ongoing circus 17, not compatible with the 0mq loop previously used).

We'll ponder if it's worth publishing that as a separate project; in the meanwhile if anybody cares he will find this thread add a comment and that will motivate us enough :-)
