### ISSUE TITLE
Running Circus as a library inside a tornado application

### ISSUE THREAD

**Issue by Notmarrco** [circus-tent/circus#1049]
Hi,
I have a tornado application running, and I would like to spawn scripts from it using circus.
But I would like to use Circus as a library, because I want to use a custom Stream Handler in my application (this stream handler returns data to frontend using server-sent events).
And it seems that tornado in circus is conflicting with tornado in my app, so I can only start() the arbiter OR start() my application. (error is ```RuntimeError: IOLoop is already running```)

I most surely am misusing this library but I can't find a way to do it another way.
Thanks,

**Comment by k4nar** [comment]
Hi,
You can pass the eventloop to the Arbiter when instantiating it. This should fix your issue.

**Comment by Notmarrco** [comment]
Thanks ! I thought I had looked there already but no.

But it doesn't work out of the box, I then had the exception ```TypeError: argument must be an int, or have a fileno() method.```, like in the issue #584. 

And I could solve it with this, as stated : 
```
import zmq
from zmq.eventloop.future import Context

ctx = Context.instance()
```

Now it's working ! thank you for your help
