### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by ztroop** [circus-tent/circus#1054]
> https://circus.readthedocs.io/en/latest/for-ops/configuration/#using-environment-variables

Using `$(circus.env.SOME_ENV_VAR)` in the configuration file ... Like so:
```
[env]
foobar = $(circus.env.SOME_ENV_VAR)
```
The application is logging ... `foobar` is a literal representation of `'$(circus.env.SOME_ENV_VAR)'`
I am interested in the value of `SOME_ENV_VAR`, not a literal representation of the key.

Is the documentation correct? My goal is to pass environment variables configured from a `docker-compose.yml` file, into the circus shell.

**Comment by k4nar** [comment]
I don't think the interpolation works in `[env]`, but it should work in `[worker]` and `[socket]`.

Is your goal to convert an env var into another? Or to pass an env var as an argument of one of your worker?

**Comment by ztroop** [comment]
To reiterate, I'm using `docker` and `docker-compose`. I'd like to be able to specify environment variables through that, and have circus respect that in some way. Does that make more sense?

**Comment by dfrankow** [comment]
I have the same issue. Any thoughts on this?

In the env section, I want things like:

```
ROOT=/foo
PYTHONPATH=$FOO/python
PATH=$PATH:$FOO/bin
```

**Comment by ztroop** [comment]
@dfrankow I never ended up getting this working. My goal was to get environment variables set in a docker container, and ideally have `circus` respect access to them. I ended up using `supervisord`, as it had better documentation and had no issues passing environment variables to my services.

**Comment by dfrankow** [comment]
Thanks! Yeah, when I was looking, supervisor didn't support python3, but it looks like they [just released a version that does](http://supervisord.org/introduction.html#platform-requirements).
