### ISSUE TITLE
circusd fails with: [ERROR] exception __init__() takes 3 positional arguments but 4 were given caught

### ISSUE THREAD

**Issue by luopio** [circus-tent/circus#1057]
Our previously working Docker-powered setup started failing yesterday with the above error. At first I thought it was something related to our code, but then I discovered that rebuilding the previously working code with `--no-cache` results in the same error. This is `circusd==0.14`. Perhaps a dependency is broken somewhere?

Here's a minimal Dockerfile that I was able to reproduce the issue with:
```
FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN pip install circus chaussette
ADD circus-test.ini ${work_dir}
CMD ["circusd", "circus-test.ini"]
```

With the `circus-test.ini` from the tutorial:
```
[circus]
statsd = 1
; httpd = 1

[watcher:webapp]
cmd = bin/chaussette --fd $(circus.sockets.web)
numprocesses = 3
use_sockets = True

[socket:web]
host = 127.0.0.1
port = 9999
```

**Comment by luopio** [comment]
Sorry for the noise. Just now noticed #1056 . Somehow escaped my previous issue searches..

**Comment by hgezim** [comment]
The fix (for now) that worked for me is:

```
pip install "PyZMQ<17.0"
pip install "tornado<5.0"
```
