### ISSUE TITLE
socket not accessible by Daphne server on Windows (due to Twisted, not Circus)

### ISSUE THREAD

**Issue by jxrossel** [circus-tent/circus#1058]
Hi,

I'm trying to run Daphne (Django channels asgi server: https://github.com/django/daphne) with the following config file:

```
[circus]
check_delay = 5

[socket:web]
host = 0.0.0.0
port = 80

[watcher:daphne]
cmd = daphne
args = --fd $(circus.sockets.web) MYAPP.asgi:application 
use_sockets = True
numprocesses = 1
```

With the socket defined above, Daphne returns an error message:
```
'NoneType' object has no attribute 'fcntl'
```
which looks to me as if the socket object is "None". I've got the same message if I just run at the command line:
```
daphne --fd 5 MYAPP.asgi:application 
```
where the file descriptor has no meaning (i.e. not associated with anything).

Remarks:

* Setting the host and port directly in the watcher args solves the issue, but then I can have only 1 process
* With the socket, Daphne receives a file descriptor number, but it's like if the number isn't associated with anything
* I'm on Windows 7 (that's maybe the issue here...)

Any help welcome here!

**Comment by k4nar** [comment]
I don't see anything wrong with your config, so maybe it's linked to Windows yes. Do you have any way to try it with Linux (a Docker container should be fine)?

**Comment by jxrossel** [comment]
Thanks for the answer! I can't test on linux at work (Windows only, no admin rights...!). I've tried to see if I could test circus with sockets in a simpler case (with another server), but I can't find another server accepting --fd and working on Windows... I'll try to see if I can test this on linux at home.

**Comment by jxrossel** [comment]
I finally managed to test it on Linux. It does work there (with same python distribution (3.6) and same version of everything else). NB: last circus release (0.15) didn't help.

**Comment by k4nar** [comment]
Yes sorry, the Windows support is not very active :/ . I managed to have a running version a few years back, but not to test it in CI. Since then there was some feedback & fixes, but not enough to guaranty that everything works as expected.

**Comment by jxrossel** [comment]
Thanks for the answer. Any hope of action towards that goal?

**Comment by k4nar** [comment]
Not by me, but it's an Open Source project :) .

**Comment by jxrossel** [comment]
@diorcety has submitted a pull request for a better Windows support (#1065). I've checked it out against this issue with no success. Just to let both of you know.

**Comment by jxrossel** [comment]
I've digged a bit more and found out that the problem lies with Twisted, on which the Daphne server is based. Twisted doesn't handle properly the opening of the socket from the inherited file descriptor on Windows. I could actually make it work by hacking Twisted a bit, even with the last stable release (i.e. without pull request #1065)
