### ISSUE TITLE
stdin process support

### ISSUE THREAD

**Issue by domenkozar** [circus-tent/circus#106]
I'm looking into using circus as message queue interface to talk to interactive console session. Last bit that is missing is sending stdin through zeromq. Does that make sense to be part of circus?

**Comment by bantl23** [comment]
I would also find this useful. Being able to interact via stdin would help in my test environments. I can change what the process does put listening on stdin. This could be done with signals but is a little more complicated. If this remains off the the feature path I can stick with supervisor which has this ability. I was just looking around at alternatives and circus seems like a really good alternative. I like the "top" like feel.
