### ISSUE TITLE
waitress

### ISSUE THREAD

**Issue by kiorq** [circus-tent/circus#1060]
Question.

Can i get this to work with waitress? If so how I've been doing research on how to use waitress and circus on a windows 2017 server. (chaussette doesn't work on windows)

**Comment by biozz** [comment]
Hi @kiorq!

[waitress](https://docs.pylonsproject.org/projects/waitress) is like almost any other server has a cli. `chausette` uses it as a backend. Please refer to waitress documentation for how to run waitress, then you can use the executable in circus configuration.

Please free to reopen the issue.
