### ISSUE TITLE
papa_endpoint ipc socket is ignored, tcp is created

### ISSUE THREAD

**Issue by meitham** [circus-tent/circus#1066]
I have three different ipc sockets defined in circus, such as:

pubsub_endpoint = ipc:///path/to//circus/sockets/circus-pubsub.sock
stats_endpoint  = ipc:///path/to//circus/sockets/circus-stats.sock
papa_endpoint   = ipc:///path/to//circus/sockets/circus-papa.sock

The pubsub and stats sockets are created correctly, but circus seems to ignore my papa socket and bind itself to the default 20202 socket.

**Comment by k4nar** [comment]
I think the error is here: https://github.com/circus-tent/circus/blob/c7d79ab72cffe77ecef0386af42943f8eaf7c86a/circus/config.py#L186
It should be `papa_endpoint` instead of `fqdn_prefix`.

**Comment by meitham** [comment]
Thanks for taking a look, and well spotted!
I have tested this and there must be something else going on too, as that fix alone didn't work, and the socket continues to be 20202.  I'm looking at ``papa_process_proxy.py`` but I can't see anything obviously wrong yet.

**Comment by meitham** [comment]
I found it!  ``papa_endpoint`` wasn't being passed to the ``Arbiter`` on initialization.  I should be able to send a PR later today.

**Comment by meitham** [comment]
PR: https://github.com/circus-tent/circus/pull/1067
