### ISSUE TITLE
bug: circusd removes pidfile on arbiter restart

### ISSUE THREAD

**Issue by imaginal** [circus-tent/circus#1080]
Don't unlink pidfile if restart is true

https://github.com/circus-tent/circus/blob/6ca0d18bd53fc5de0358921f45fbbd609a884f6a/circus/circusd.py#L165

**Comment by k4nar** [comment]
Hum, is the bug that it's not re-created afterwards?

**Comment by imaginal** [comment]
@k4nar I think not. Pid of process not changed, why it should be recreated?
