### ISSUE TITLE
config file options have different types in different files

### ISSUE THREAD

**Issue by mercma** [circus-tent/circus#1088]
I have found the following two options (possibly others) have different types in different files:

warmup_delay
graceful_timeout

example:
in config.py line 240, graceful_timeout is read as an int, but:
in watcher.py line 222, graceful_timeout is cast to a float

If you attempt to define graceful_timeout as a float in your ini file, circus will not start.
If they are being used internally as 'float', why can I not define them that way in the config file?  Should they be 'int' or 'float'?  Was this decision part of the design?

Thanks,
Mike

**Comment by k4nar** [comment]
Yes a float would should be a valid option.
