### ISSUE TITLE
Process fails to start with on_demand = False option in watcher

### ISSUE THREAD

**Issue by mercma** [circus-tent/circus#1091]
In the example watcher below,

```
[watcher:exec]
args = /root/circus/exec.py
cmd = /usr/bin/python3
on_demand = False
```
the process will not start when on_demand is set as False in the configuration file.

This is caused by [watcher.py]:
```
@property
def pending_socket_event(self):
    return self.on_demand and not self.arbiter.socket_event
```
which is called from [watcher.py[
```
@gen.coroutine
@util.debuglog
def _start(self):
    """Start.
    """
    if self.pending_socket_event:
        return

...
```

If the on_demand option is removed from the watcher section, the process will execute as expected, even though the documentation states that False is the default value for on_demand.

**Comment by biozz** [comment]
This was fixed in #1089.
