### ISSUE TITLE
Changelog @ readthedocs.io requires an update

### ISSUE THREAD

**Issue by jeroenhendricksen** [circus-tent/circus#1098]
The 'Changelog History' website at [readthedocs.io](https://circus.readthedocs.io/en/latest/changelog/) states `0.15.0 unreleased`. This should be updated as 0.15.0 is the latest stable release and is no longer 'unreleased'.

Not sure if circus.readthedocs.io is under your control, so please close this issue if you can't amend the text there.

**Comment by k4nar** [comment]
I've fixed the date in the changelog, thanks :+1: . I think the doc won't be updated until the next tag though, there is not much I can do.
