### ISSUE TITLE
Circus forcing PyZMQ <17.0

### ISSUE THREAD

**Issue by cmcgrath13** [circus-tent/circus#1099]
We are attempting to integrate circus with our product which uses PyZMQ 17.0 and found that circus has the requirement `pyzmq>=13.1.0,<17.0'`. When attempting to run our code with the requirement `pyzmq>=13.1.0,<17.0'` we get issues with the zmq socket handling. 

We see in #1055 circus has compatibility issues with PyZMQ 17.0 so it would be inadvisable to attempt to force circus onto our required version of PyZMQ. We are working on putting circus inside a venv to circumvent this issue, but feel if circus is going to require an older version of PyZMQ it should be vendoring it to work inline with solutions requiring a newer version of PyZMQ.

**Comment by k4nar** [comment]
I would very much appreciate any contribution bringing compatibility with recent versions of PyZMQ :) .

**Comment by k4nar** [comment]
I wouldn't recommend vendoring PyZMQ to be honest, as this is a dependency which need some compilations, and a system dependency at the right version…

I would very much like to see Circus compatible with the latest version of PyZMQ (and tornado) though.

**Comment by dlopuch** [comment]
`jupyter`'s `notebook` requires pyzmq>=17, so people deploying data science-y things are going to have this incompatibility with circus. +1

**Comment by ltalirz** [comment]
just as a practical side note for people dealing with the `notebook` incompatibility issue: according to these comments
https://github.com/jupyter/notebook/blob/b8e30ea84bd614a193f5233cc875440e4580d12a/setup.py#L83-L85
the `notebook` up until the latest release 5.7.8 actually works fine also with `pyzmq<17`

However, the latest master branch now already has the `tornado>=5` requirement
https://github.com/jupyter/notebook/blob/eea37a6b2110e0b8a5491f17e241fa3c8aecb5f7/setup.py#L101
