### ISSUE TITLE
Virtualenv not finding modules

### ISSUE THREAD

**Issue by jebesen** [circus-tent/circus#1101]
I am executing this circus.ini:

`[circus]

[watcher:dataservice]
cmd = chaussette --fd $(circus.sockets.dataservice) --backend tornado run.app
use_sockets = True
numprocesses = 3
respawn = False
priority = 1
virtualenv = env
virtualenv_py_ver = 3.6
working_dir = service
copy_env = True
copy_path = True

[socket:dataservice]
host = 0.0.0.0
port = 8000`

And it gives me this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/chaussette/util.py", line 124, in import_string
    __import__(modname)
  File "./app.py", line 1, in <module>
    from flask import Flask, request, current_app, abort, jsonify
ModuleNotFoundError: No module named 'flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/chaussette", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/chaussette/server.py", line 173, in main
    app = import_string(application)
  File "/usr/local/lib/python3.6/dist-packages/chaussette/util.py", line 129, in import_string
    sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/chaussette/util.py", line 124, in import_string
    __import__(modname)
  File "./app.py", line 1, in <module>
    from flask import Flask, request, current_app, abort, jsonify
chaussette.util.ImportStringError: import_string() failed for 'app.app'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'app' not found.

Original exception:

ModuleNotFoundError: No module named 'flask'`

I do not understand since flask is installed in the virtualenv folder.  If I install flask globally in the system, circusd works propperly, but I want it to use the virtualenv installation.

**Comment by beezz** [comment]
You need to install and use `chaussette` from that virtualenv as well. From the logs it looks like you are running the system installed one.

You can pass full path to the `chaussette` binary ~ `/path/to/your/virtualenv/bin/chaussette --fd $(circus.sockets.dataservice) --backend tornado run.app` to be sure that you are using the right virtualenv.

**Comment by jebesen** [comment]
Thank you.

I have just chanched the path to chaussette and also added the full path to the virtualenv parameter.  Now it is working.

**Comment by jebesen** [comment]
Thank you.

I have just chanched the path to chaussette and also added the full path to the virtualenv parameter.  Now it is working.
