### ISSUE TITLE
Is the Tornado version being updated?

### ISSUE THREAD

**Issue by jlariza** [circus-tent/circus#1107]
The next celery flower version will not be compatible with Tornado < 5. I am using circus to start flower process, so I will not be able to keep using this library once flower 1.x is released.

Is Tornado support being considered?

**Comment by k4nar** [comment]
I don't think there as been any effort to support newer versions of Tornado yet. Contributions are welcome :) .

**Comment by csadorf** [comment]
@k4nar Do you have an estimate of how much effort it might take to make circus compatible with the tornado 5 or 6 line?

**Comment by k4nar** [comment]
I would say it's not trivial. If I remember correctly we would have to update ZMQ at the same time.

**Comment by amirzamli** [comment]
Any update on this?

**Comment by biozz** [comment]
Closing in favor of #1124 and #1130.
