### ISSUE TITLE
Is there is a way to interpolate the watcher's name in the configration file

### ISSUE THREAD

**Issue by tinylambda** [circus-tent/circus#1114]
In supervisor we can configure the stdout logfile like this

```
[program:chaos_http]
stdout_logfile = /tmp/log/supervisor/%(program_name)s.log
...
```

in which we can use  the variable **program_name** as part of the logfile.

Is there is way to do things like this in circus ?

```
[watcher:myprogram]
cmd = python -m myapp.server

stdout_stream.class = TimedRotatingFileStream
stdout_stream.filename = /tmp/%(watcher_name)s.log
....
```

where watcher_name will be replaced by myprogram when get the option;

Thanks!

**Comment by k4nar** [comment]
There are some substitution possibilities (like `$(circus.env.<var>)`), but I don't think that the watcher options are part of it, sorry. I could probably be added though.

**Comment by tinylambda** [comment]
> There are some substitution possibilities (like `$(circus.env.<var>)`), but I don't think that the watcher options are part of it, sorry. It could probably be added though.

Thanks for the reply, and I managed to get it works by do the substitution on a higher level.

**Comment by k4nar** [comment]
Do you have an example for future persons stumbling upon this? :)

**Comment by tinylambda** [comment]
> Do you have an example for future persons stumbling upon this? :)

No magic here. I just do the follow things:

1. Configure the filename option to a Python format string template (in a dictionary):
``` 
    'stderr_stream.class': 'FileStream',
    'stderr_stream.filename': os.path.join(CIRCUSD_LOG_ROOT_DIR, '{watcher_name:s}.error.log'),
    'stderr_stream.time_format': '%%Y-%%m-%%d %%H:%%M:%%S',
    'stderr_stream.max_bytes': '1073741824',
    'stderr_stream.backup_count': '5',
    'stdout_stream.class': 'FileStream',
    'stdout_stream.filename': os.path.join(CIRCUSD_LOG_ROOT_DIR, '{watcher_name:s}.info.log'),
    'stdout_stream.time_format': '%%Y-%%m-%%d %%H:%%M:%%S',
    'stdout_stream.max_bytes': '1073741824',
    'stdout_stream.backup_count': '5',
```


2. Collect the render context  and put them to a dictionary, then use it to render the option values:
```
for CIRCUS_WATCHER in CIRCUS_WATCHERS:
    name = CIRCUS_WATCHER['name']
    watcher_settings = CIRCUS_WATCHER['settings']
    settings = copy.copy(CIRCUS_WATCHER_DEFAULT_SETTINGS)
    settings.update(watcher_settings)
    section_name = f"watcher:{name}"
    render_context = {"watcher_name": name}

    CIRCUSD_CONFIG.add_section(section_name)
    for setting_key in settings:
        setting_value = settings[setting_key]
        setting_value = setting_value.format(**render_context)
        CIRCUSD_CONFIG.set(section_name, setting_key, setting_value)
```

Done.

**Comment by k4nar** [comment]
Ok, thanks!
