### ISSUE TITLE
The documentation on readthedocs is not being updated

### ISSUE THREAD

**Issue by biozz** [circus-tent/circus#1122]
I noticed that documentation on https://circus.readthedocs.io/ is not being updated. For example, the latest changelog entry is still 0.15.0 - https://circus.readthedocs.io/en/latest/changelog/

Is the deployment of the docs automated? I couldn't figure that out.

**Comment by k4nar** [comment]
Indeed, the webhook in Read The Docs is broken. However, I don't have the rights to activate it.

@tarekziade : if you stumble upon this by any chance, could you take a look? :)

**Comment by k4nar** [comment]
I'm now maintainer in Read The Docs thanks to Tarek, and it seems that the webhook was fixed :+1: .

**Comment by k4nar** [comment]
Hum actually the build on master is still failing.

**Comment by tarekziade** [comment]
It was using python 2. I fixed it

**Comment by k4nar** [comment]
I fixed it at the same time I think :smile: . Anyway, now it builds, and the webhooks look green again \o/ .
