### ISSUE TITLE
New Release with new Tornado

### ISSUE THREAD

**Issue by demosdemon** [circus-tent/circus#1130]
Is there any chance we could get a new (possibly alpha/beta) with the updated python & Tornado dependencies? There is a bugfix in Tornado 5.1.0 I need, but I would like to avoid git-based dependencies if possible.

**Comment by k4nar** [comment]
Yes, we should definitively do a release, changes are getting pretty big now thanks to @biozz & @unkcpz :) .

I'll take a look at the latest PR & do the release as soon as possible.

**Comment by k4nar** [comment]
I've just released Circus 0.17.1 with the support of recent Tornado versions. Sorry for the delay!
