### ISSUE TITLE
Update libzmq-dev to libzmq3-dev in the docs

### ISSUE THREAD

**Issue by Sangarshanan** [circus-tent/circus#1138]
When trying to follow the step-by-step tutorial, installation of `libzmq`  failed on my machine `Ubuntu 18.04.4 LTS` a quick search revealed that newer Ubuntu versions don't provide this package and I need to use `libzmq3-dev` instead 

Thought it would help to either update the name or include a note in the docs if that's ok : )

**Comment by biozz** [comment]
Hi @Sangarshanan!

Thank you for pointing that out. I see that there are couple of other outdated things on this page. I will have a look at it.
