### ISSUE TITLE
Add Python3.9 and PyPy to support list

### ISSUE THREAD

**Issue by tinylambda** [circus-tent/circus#1183]
As we use circus in Python 3.9 environment, and we also test it in a PyPy environment, it works well, I think it's time to add Python 3.9 and PyPy to circus's support list and run unittests in these environment in the CI flow.

@k4nar

**Comment by k4nar** [comment]
Indeed, I think we should drop support for Python 3.5 and 3.6, and add official support for Python 3.9 & 3.10.

If Circus also runs on PyPy that's great, I believe it wasn't the case at some point. It should be added to our CI.

Do you think you could make the changes?

**Comment by tinylambda** [comment]
> Indeed, I think we should drop support for Python 3.5 and 3.6, and add official support for Python 3.9 & 3.10.
> 
Agree.

> If Circus also runs on PyPy that's great, I believe it wasn't the case at some point. It should be added to our CI.
> 
Agree.

> Do you think you could make the changes?
I can add Python 3.9 to support list and add Python 3.9 and PyPy to our CI flow.

**Comment by tinylambda** [comment]
Done by https://github.com/circus-tent/circus/pull/1182
