### ISSUE TITLE
fix the ssh test

### ISSUE THREAD

**Issue by tarekziade** [circus-tent/circus#228]
playing with the user ssh key is a very bad idea. if the test fails or something goes wrong, he can lose  his private keys.

the test needs to work in complete isolation from the rest of the system.

btw, this:

```python
SSH_PATH = '/home/' + os.getlogin() + '/.ssh/'
```

WIll not work under OS X. You want:

```python
SSH_PATH = os.path.expanduser(os.path.join('~', os.getlogin() + '.ssh'))
```

**Comment by k4nar** [comment]
I don't think this test exists anymore.
