### ISSUE TITLE
re-think debug options to allow per-watcher log.

### ISSUE THREAD

**Issue by almet** [circus-tent/circus#278]
( cc @natim @lothiraldan )

Currently, either we debug all the watchers and everything in circus, ot we don't do anything. That could be handy to specify which watcher should we debug and which one we shouldn't.

This is  spinning off from #270

I propose that we add a `log_level` param to each watcher. We then could map this to a specific logger (a child of the "circus" logger for instance?) and let logging handle this for us.

**Comment by k4nar** [comment]
Closing it in favor of #270
