### ISSUE TITLE
Add scheduling

### ISSUE THREAD

**Issue by nickray** [circus-tent/circus#319]
This is a bit of a big request/idea, differing from the web server background that this project seems to be coming from. What I personally need is a way to schedule processes to run from time A to time B per day, with time specified using a timezone. Are there any plans in this direction?

If there is interest, I can flesh out the requirements, and possibly work on an implementation.

**Comment by k4nar** [comment]
I'm closing this as there was no momentum since almost 3 years. Plus as said before, this can be done outside circus via circusctl or ZMQ.
