### ISSUE TITLE
no stderr / stdout in the log files

### ISSUE THREAD

**Issue by krychu** [circus-tent/circus#453]
Hi,
I'm using chaussette with circus and meinheld. But I cannot get any stderr / stdout messages from the webapp even though these streams are redirected to the log files. I know that the webapp throws some exceptions but the log files are completely empty. If I run webapp manually without using chaussette I do get all messages in the console. Can it be that chaussette swallows the messages? Or perhaps meinheld? Or perhaps I'm missing something in the configuration? Or perhaps stderr / stdout are not correctly captured because of the virtualenv / copy_env ?

Below is my circus.ini file. Thanks

``` [circus]
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
stats_endpoint = tcp://127.0.0.1:5557
httpd = True
httpd_host = 0.0.0.0
httpd_port = 8080
debug = True

[watcher:web]
working_dir = /home/k/projects/g/src/webapp
copy_env = True
virtualenv = /home/k/projects/g/ENV
cmd = chaussette --fd $(circus.sockets.web) --backend meinheld webapp.app
use_sockets = True
numprocesses = 1
warmup_delay = 5

# stdout_stream.class = StdoutStream
# stderr_stream.class = StdoutStream

stderr_stream.class = FileStream
stderr_stream.filename = /var/log/webapp_err.log
stderr_stream.refresh_time = 0.3
# rotate the log file when it reaches 1 gb
# and save N copies of rotated files
stderr_stream.max_bytes = 1073741824
stderr_stream.backup_count = 2

stdout_stream.class = FileStream
stdout_stream.filename = /var/log/webapp_out.log
stdout_stream.refresh_time = 0.3
# rotate the log file when it reaches 1 gb
# and save N copies of rotated files
stdout_stream.max_bytes = 1073741824
stdout_stream.backup_count = 2
```

**Comment by aventurella** [comment]
@krychu what ended up being the solution? I have a similar issue (using Celery) but my logs don't seem to go into the file. I'm using python's built in logger and running celery (3.1.17)

**Comment by aventurella** [comment]
nevermind... looks like celery sends it's logs to stderr, I had thought it was stdout =(

**Comment by matleh** [comment]
In my experience, print output is often not shown in the logs because of buffering. 
If you add `PYTHONUNBUFFERED=1` to the [env] section in `circus.ini`, print output finds its way into the logs immediately. Not sure, what other side effects that might cause.

**Comment by antgel** [comment]
FWIW, I see the same as matleh.  On my system, the logs just don't get written even after restarting the process, unless I add PYTHONUNBUFFERED=1.
