### ISSUE TITLE
load_virtualenv crashes when virtualenv has a different Python version

### ISSUE THREAD

**Issue by cgarciaarano** [circus-tent/circus#688]
I'm trying to run a Django app via chaussette. This app uses a virtualenv using Python 2.6, but the system Python binary is Python 2.7.

If I use virtualenv configuration directive, circus just crashes, without any log whatsoever.

My configuration:

```
[watcher:my_django_app]
working_dir = /path/to/my_django_app
cmd = /usr/local/bin/chaussette --fd $(circus.sockets.my_django_app) --backend gevent my_django_app.wsgi.application
use_sockets = True
copy_env = True
copy_path = True
numprocesses = 1
virtualenv = /path/to/my_django_app/env/

[socket:my_django_app]
host = 127.0.0.1
port = 8012

[env:my_django_app]
PYTHONPATH = /path/to/my_django_app
```

I've been reading Issue #351 and I think that the problem is that `py_ver` it's taking the version from the Python binary which is executing circus. See the code below:

```python
    py_ver = sys.version.split()[0][:3]

    # XXX Posix scheme - need to add others
    sitedir = os.path.join(watcher.virtualenv, 'lib', 'python' + py_ver,
                           'site-packages')

    if not os.path.exists(sitedir):
        raise ValueError("%s does not exist" % sitedir)
```

I'm not sure if it's a bug or a lack of feature, but I think that the exception raised is not being handled correctly and that causes Circus to crash. I've not checked this statement, though.

...or maybe I just have a configuration problem.

**Comment by k4nar** [comment]
It should work now if you add `virtualenv_py_ver=2.6` to your watcher configuration, thanks to #805.
