### ISSUE TITLE
Why circus is not getting start/stop ?

### ISSUE THREAD

**Issue by celhanson** [circus-tent/circus#725]
I am using circus server to run python program as a daemon process. But now circus is not getting started or stop or not even the status of the circus i get to know.

I tried with the :

sudo circusctl restart <name_of_repository>
sudo circusctl stop
sudo circusctl start
sudo circusctl status

But all the commands gives me following error :

Timed out. Try to raise the --timeout value

should anyone know about this error. Please help me thanks in advance..

**Comment by k4nar** [comment]
No response in two years, I'm closing it.
