### ISSUE TITLE
Memory leak in circusd

### ISSUE THREAD

**Issue by scottkmaxwell** [circus-tent/circus#732]
Normally circusd is consuming about 32M of RAM, but some of our instances end up consuming several GB. Must be a memory leak somewhere.

I am going to add a config option so we can set ``gc.set_debug(gc.DEBUG_LEAK)`` and also add a ``debuginfo`` command. I'm thinking about making [objgraph] (https://mg.pov.lt/objgraph/) an optional dependency so that the ``debuginfo`` command can output a bunch of data and images that objgraph outputs.

**Comment by k4nar** [comment]
A lot have changed since that issue, I'm closing it. Please open a new issue if you see something similar.
