### ISSUE TITLE
circus fails to reloadconfig if watchers exists with capitalized/uppercased names

### ISSUE THREAD

**Issue by daenney** [circus-tent/circus#823]
When there's a watcher defined like so:

```ini
[watcher=HELLO123]
cmd = /bin/echo hello
```

Circus fails to reload when calling `reloadconfig` with the following error in the logs:

```
circus[8523] [ERROR] exception 'HELLO123' caught
```

As an added bonus, if circus is restarted, through the init-script, it actually manages to load and start the watcher but any further call to `reloadconfig` fails, even if the configuration is changed to lowercase.

**Comment by daenney** [comment]
@olafz @eagllus So this is fixed now.

**Comment by olafz** [comment]
:+1:
