### ISSUE TITLE
Long running graceful timeouts

### ISSUE THREAD

**Issue by max0d41** [circus-tent/circus#847]
We have some apps that are doing very long-running tasks that should stay alive until all tasks are complete.

Nginx for eg. has a very nice reload feature where the old workers are marked in the process list as `nginx: worker process is shutting down`, and they are running until every request is done. Depending on the service that is running behind nginx it could take days until all old nginx processes are gracefully shut down.

The current graceful feature of circus is useable for timeouts in the range of a few seconds since in the meantime all start/stop/restart/... commands are blocked.

Does anyone have an idea for a workaround to get such behavior with circus? Or maybe someone will add such a functionality to circus...

**Comment by k4nar** [comment]
I'm not sure what's needed in Circus there. Setting the `autorestart` option to `False` for this watcher using circusctl isn't enough?

**Comment by max0d41** [comment]
I realized such a feature using a `before_signal` hook.

The hook removes the stopped process completely from circus. It assumes that the process that is stopped/restarted sets it's name to something like "(dying since \d+ seconds)".

```python
import re
import os
import psutil

from signal import SIGTERM

from circus import logger
from circus.watcher import Watcher
from circus.process import DEAD_OR_ZOMBIE, UNEXISTING


# Function to check if the process is dying

pattern = re.compile(r'^.+ \(dying since \d+ seconds.*\)$')

def process_is_dying(pid):
    p = psutil.Process(pid)
    if pattern.match(p.name()):
        logger.info('Process with PID %s and name "%s" is dying', p.pid, p.name())
        return True
    return False


# Monkey patch Watcher.manage_processes function

def _Watcher_manage_processes(self):
    for process in list(self.processes.values()):
        if process.status in (DEAD_OR_ZOMBIE, UNEXISTING):
            self.processes.pop(process.pid)
        else:
            # The return value of name() is cached at psutil class so we have to create a new process
            try:
                if process_is_dying(process.pid):
                    self.processes.pop(process.pid)
            except:
                pass

    return _old_Watcher_manage_processes(self)

if Watcher.manage_processes != _Watcher_manage_processes:
    _old_Watcher_manage_processes = Watcher.manage_processes
    Watcher.manage_processes = _Watcher_manage_processes


# Circus hook

def before_signal(watcher, arbiter, hook_name, pid, signum):
    """This hook is a "before_stop" hook."""
    if signum == SIGTERM:
        try:
            os.kill(pid, SIGTERM)
        except OSError as e:
            if e.errno != 3:
                raise
        watcher.processes[pid]._worker = psutil.Popen(['/bin/true'])
    return True
```

**Comment by k4nar** [comment]
Okay great :) . I'm closing this as I don't think Circus really need an option for that, as long as there is a workaround.

Thanks for sharing your solution!
