### ISSUE TITLE
pyyaml is not optional

### ISSUE THREAD

**Issue by thefunny42** [circus-tent/circus#851]
The code in circus.util does support it optionally, but it is in the list of install_requires in setup.py. Would it possible to make it really optional ?

**Comment by k4nar** [comment]
`pyyaml` is not required since 87963d7398ad94d75c624d3e9e942fc261475b08. However we should add an useful message when trying to parse a yaml file without the dependency. Also it's still required for the tests.

**Comment by k4nar** [comment]
Actually this is already the case (cf: https://github.com/circus-tent/circus/blob/88dc97e6e8a2f222201ad13abe25cc0c6dca1f2f/circus/util.py#L723-L727).
