### ISSUE TITLE
python 2.6 compat

### ISSUE THREAD

**Issue by tarekziade** [circus-tent/circus#855]
Looks like zmq is not 2.6 compatible anymore https://travis-ci.org/circus-tent/circus/jobs/38821476#L135

maybe we should drop 2.6 compat?

**Comment by k4nar** [comment]
Indeed that was an error (cf http://zeromq.github.io/pyzmq/changelog.html#id2).

I don't think that 2.6 compatibility has a big influence on the code, and it's still needed by some people.
