### ISSUE TITLE
Document where hooks files should go

### ISSUE THREAD

**Issue by dpkirchner** [circus-tent/circus#867]
AFAICT there's no documentation describing where hooks files should go. Worse, if you specify a hook that does not exist no error is logged to the circus log file. That's a separate bug (in 0.11.1) but if it logged the documentation might not be quite as necessary.

**Comment by ayashjorden** [comment]
+1, wasting a lot of time to understand it and no success.
 @dpkirchner did you get hooks to work ?

**Comment by douardda** [comment]
hooks are python modules, and are configured as this module "path"; as such, they must be available somewhere in the PYTHONPATH.

It's not explicitely documented (this should be, I agree), but https://circus.readthedocs.org/en/latest/for-devs/writing-hooks/?highlight=hook gives examples like:
 
```
[watcher:queue-worker]
cmd = python -u worker.py
hooks.before_start = mycoolapp.myplugins.check_redis
```

which seems pretty clear (to me).

**Comment by ayashjorden** [comment]
I've executed:
```
 ⋯  circus   master  …  59ec339  source bin/activate
 ⋯  circus   master  …  59ec339  python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/yarden/dev/utils/circus/lib/python2.7', '/home/yarden/dev/utils/circus/lib/python2.7/plat-x86_64-linux-gnu', '/home/yarden/dev/utils/circus/lib/python2.7/lib-tk', '/home/yarden/dev/utils/circus/lib/python2.7/lib-old', '/home/yarden/dev/utils/circus/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages', '/home/yarden/dev/utils/circus/lib/python2.7/site-packages']
```
Directory structure:
```
 ⋯  circus   master  …  59ec339  ls -l
total 28
drwxr-xr-x 2 yarden yarden 4096 Jun 29 12:08 bin
-rw-r--r-- 1 yarden yarden  278 Jun 29 12:43 circus.ini
drwxr-xr-x 2 yarden yarden 4096 Jun 29 12:43 hooks
drwxr-xr-x 2 yarden yarden 4096 Jun 29 12:07 include
drwxr-xr-x 3 yarden yarden 4096 Jun 29 12:07 lib
drwxr-xr-x 2 yarden yarden 4096 Jun 29 12:35 local
-rw-r--r-- 1 yarden yarden   60 Jun 29 12:08 pip-selfcheck.json
```

```
 ⋯  circus   master  …  59ec339  circusd ./circus.ini 
Traceback (most recent call last):
  File "/home/yarden/dev/utils/circus/bin/circusd", line 9, in <module>
    load_entry_point('circus==0.12.0', 'console_scripts', 'circusd')()
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/circusd.py", line 126, in main
    arbiter = Arbiter.load_from_config(args.config)
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/arbiter.py", line 426, in load_from_config
    watchers.append(Watcher.load_from_config(watcher))
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/watcher.py", line 401, in load_from_config
    w = cls(name=config.pop('name'), cmd=config.pop('cmd'), **config)
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/watcher.py", line 311, in __init__
    self._resolve_hooks(hooks)
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/watcher.py", line 389, in _resolve_hooks
    self._resolve_hook(name, callable_or_name, ignore_failure)
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/watcher.py", line 378, in _resolve_hook
    reload=reload_module)
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/util.py", line 608, in resolve_name
    raise_with_tb(ImportStringError(import_name, e))
  File "/home/yarden/dev/utils/circus/local/lib/python2.7/site-packages/circus/util.py", line 595, in resolve_name
    return __import__(import_name)
circus.util.ImportStringError: import_string() failed for 'hooks.detect_crash.super_hook'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'hooks' not found.

Original exception:

ImportError: No module named hooks.detect_crash.super_hook
```

Any idea?
Maybe it worth of providing a more detailed example to (new python) users.

Thanks,
Yarden

**Comment by douardda** [comment]
is your hooks directory a python package? (and nested sub packages)

There must be a (possibly empty)  __init__.py file in any directory along the hook's path. Here, I guess there is a hooks/detect_crash.py file in which the super_hook function is defined. 
If true, you only need a hooks/__init__.py file so the hooks directory is considered a valid python package.

**Comment by ayashjorden** [comment]
AFAIK there should be a ```__init__.py``` file, and it exists.
what is ```init.py``` ?

**Comment by ayashjorden** [comment]
Hooks directory listing:
```
 ⋯  logstash-configuration   master  +1  08cea5d  1  ls -l ~/dev/utils/circus/hooks/
total 12
-rw-r--r-- 1 yarden yarden 243 Jun 29 12:43 detect_crash.py
-rw-r--r-- 1 yarden yarden 450 Jun 29 12:36 detect_crash.pyc
-rw-r--r-- 1 yarden yarden   0 Jun 29 11:46 __init__.py
-rw-r--r-- 1 yarden yarden 104 Jun 29 12:36 __init__.pyc
```

**Comment by ayashjorden** [comment]
Any update here, this is a blocker for me :)

**Comment by dpkirchner** [comment]
@ayashjorden

I did, although I ran in to other issues I could not resolve and I think
we're going to be dropping all hook use.

For what it is worth, our circus configs are in /etc/circus, and our hook
line is basically:

hooks.after_spawn = plugins.some_name.some_method

We added PYTHONPATH=/etc/circus to our init script that starts circusd. All
of this meant that the plugin had to go in
/etc/circus/plugins/some_name.py. There had to be a __init__.py boilerplate
file as is required for python modules -- ours is an empty file.

@douardda

It wasn't clear that the module had to be in PYTHONPATH. I know now that it
does but I'm not really comfortable putting such specific plugins in the
global path, where package managers such as apt-get and pip roam, so I
ended up doing what I describe above.

**Comment by ayashjorden** [comment]
Thanks @dpkirchner, this is indeed working :)

Now, I'm trying to understand how to catch the event when a perocess got killed (kill -KILL 12334)

**Comment by douardda** [comment]
@dpkirchner it's best to use the [env:xxx] section to configure environment variables, in this case, a specific PYTHONPATH

Also, I don't understand your  sentence "putting such specific plugins in the global path".

**Comment by ayashjorden** [comment]
From what i've experimented today, hooks are not the tool for catching process crash events.

**Comment by ayashjorden** [comment]
Using logger plugin example I was able to get process crash event.

**Comment by dpkirchner** [comment]
@douardda re: global path. If I didn't set the `PYTHONPATH` I'd have to install the plugins somewhere like `/usr/lib/python2.7` or wherever python looks by default. I'm not comfortable with that because I also use `apt` and `pip` to install python packages (the combination of which are already a big problem).

**Comment by davidbirdsong** [comment]
Agreed, this is the single reason I haven't invested in hooks as much as I'd like to with the burden shifted to the user having to concoct a sensible deploy strategy. One that doesn't trample on the system package manager.

It would be great if both:
```ini
[circus]
```
and 
```ini
[watcher:<myprogram>]
```
could specify a hooks import path.

**Comment by prokher** [comment]
It is rather inconvenient to use PYTHONPATH in order to specify hooks location. Doing this externally is just weird. In my case, the file with hooks is located inside my project (since it is project-specific) and I had to `[env:program] PYTHONPATH=.`. (I can not use absolute path, since I do not know where it is run.)

**Comment by davidbirdsong** [comment]
+1

**Comment by prokher** [comment]
I see three useful alternatives:

1. treat module name relative to cwd
2. treat it relative to the configuration file used
3. behave like it is now (just import as is, relying on PYTHONPATH)

I think, it would be great to have ability to explicitly pick one of the enlisted variants.

**Comment by pconerly** [comment]
Also, why not all three of @prokher 's suggestions?

I was trying to get around the hook problem by using a plugin instead-- but I'm running into the same problem with plugins too-- I want to have a plugin file `circus_config.py` with function `def filewatcher` that's a sibling to cwd and the `.ini`. And it's not being found, since it's not being added to sys.modules when circusd runs :-/

Any updates or ideas on this? I browsed the open PRs in hopes that someone had written some code for this. :3
