### ISSUE TITLE
Multicast Error

### ISSUE THREAD

**Issue by geekrohit** [circus-tent/circus#875]
Getting this while starting circusd : 
    2015-02-09 07:37:12 circus[67550] [WARNING] Multicast discovery is disabled, there was an error during udp socket creation.
Traceback (most recent call last):
  File "/opt/local/lib/python3.4/site-packages/circus/controller.py", line 61, in _init_multicast_endpoint
    multicast_port)
  File "/opt/local/lib/python3.4/site-packages/circus/util.py", line 927, in create_udp_socket
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 255)
OSError: [Errno 22] Invalid argument

circus.ini contains : 
[circus]
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
stats_endpoint = tcp://127.0.0.1:5557
statsd = True

Multicast is enabled on the interface.
OS is SunOS. 

I've tried same in py2.7, same error. Any pointers ? 
Due to the above error, not able to start web interface.

Thanks

**Comment by k4nar** [comment]
I guess there is something wrong with Multicast discovery and SunOS. cc @Natim 

However that's weird because it seems to be supported: http://docs.oracle.com/cd/E23824_01/html/821-1602/sockets-137.html

**Comment by Lothiraldan** [comment]
It's strange, could you try to change the value of socket.IP_MULTICAST_TTL from 255 to 1 ?

sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 255) -> sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 1)

**Comment by k4nar** [comment]
I think this may solve the issue: http://stackoverflow.com/questions/603852/multicast-in-python/21332405#21332405

Could you try to make that change in `create_udp_socket` (`circus/util.py`) ?

**Comment by geekrohit** [comment]
@Lothiraldan , changing 255 to 1 doesn't work. 

@k4nar That did the trick.
Added : 
import struct
ttl = struct.pack('B', 2)

and changed 255 to ttl. I confirmed using netstat. 

Had to make same changes in circushttp/utils.py for it to work.

**Comment by k4nar** [comment]
Great :) . I don't know if we can do that on every platform, or if we should use some platform detection.

**Comment by geekrohit** [comment]
Well, its in the startup code, so I think there won't be much overhead if you were to go the detection route.

**Comment by geekrohit** [comment]
I can check it on FreeBSD if required.

**Comment by k4nar** [comment]
That would be great, thanks. Can you open a pull request ?

**Comment by geekrohit** [comment]
Ok, great. I will setup clean VMs for the above tasks, and check it on all 3 systems, SunOS, BSD, Linux.

**Comment by Lothiraldan** [comment]
Thank you very much @k4nar and @geekrohit for the debugging, it's strange that this code is not portable.

**Comment by Lothiraldan** [comment]
It's unfortunately a known issue http://bugs.python.org/issue23127 but won't be fixed, the description of the bug let me thinks that BSD will require the patch too.

**Comment by geekrohit** [comment]
The above struct patch doesn't raise any errors on Linux (Ubuntu 14.04 LTS, Python 2.7) , and netstat confirms that its listening on the desired multicast port ( set by multicast_endpoint = udp://224.1.1.1:12027).

I used : 
`
ttl = struct.pack('B',255)
`
`
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, ttl)
`

**Comment by geekrohit** [comment]
Confirmed working on SunOS Python 3.4 as well. Are there any more ways I can test other than netstat ?  
For now am not aware of how multicast is used, any pointers there ?

**Comment by Lothiraldan** [comment]
Multicast is used to automatically discover circusd instances across the network. It's used in circus-web when you have multiple circusd instances and will maybe used for circusd cluster features.

**Comment by geekrohit** [comment]
Tested circus on FreeBSD 10, it works without any changes, clean install. So its only the SunOS that is affected.
However, I tried out the struct changes, FreeBSD's circus still functions normally.
