### ISSUE TITLE
"recursive" of signal command not really recursive

### ISSUE THREAD

**Issue by matleh** [circus-tent/circus#880]
"recursive" only sends the signal to the process and its direct children, but not its grand-children, as the name makes one believe.

I bumped into that when I wanted to kill a process and all its decendants with `signal mywatcher --recursive SIGKILL` which left processes behind (which in turn hindered new processes to start again, since ports where still in use ...).

Could "recursive" really be recursive?

**Comment by k4nar** [comment]
I guess it could be added quite simply by adding `recursive=True` to this line: https://github.com/circus-tent/circus/blob/2a38dade7bbd14fa0530832fb56f6e3752d06ef2/circus/process.py#L536

Do you want to try to make a patch ?

**Comment by matleh** [comment]
I had a quick look at it but it did not seem to be as easy as suggested. Will have to take some more time for this.

**Comment by matleh** [comment]
Sorry, Iooked at the wrong place. Actually, it is quite simply - the hard part is the test for this.

**Comment by k4nar** [comment]
Closed by #888
