### ISSUE TITLE
Watcher performance issue

### ISSUE THREAD

**Issue by b4stien** [circus-tent/circus#883]
I recently ran into a really weird performance issue which lead me to write this SO question: http://stackoverflow.com/questions/29379868/celery-important-slowdown-on-subprocess.

After investigating a bit it turned out that Celery was taking 3x more time to process my job when launched/managed by Circus than it took when launched "manually" (or supervised by Supervisor).

My config file for this watcher was (as far as I can remember - I didn't keep an exact copy, sorry):

```
[watcher:foo-celery]
cmd = /home/admin/.envs/foo/bin/celery -A foo.celery worker --loglevel=info -B
copy_env = True
virtualenv = /home/admin/.envs/foo/

uid = admin
working_dir = /home/admin/foo/

stderr_stream.class = FileStream
stderr_stream.filename = /home/admin/foo/logs/celery.log
```

I'm sorry I don't have the time to give you a clean reproducible example.

And btw it's not Celery specific: I switched to rq to see if it wasn't coming from there, and the results were the same.

**Comment by k4nar** [comment]
I don't really what could be causing this behavior, except maybe the `FileStream`. I'll try to run some tests.

**Comment by b4stien** [comment]
No output was sent to stderr during the profile shown in the SO question, and in general the output was really low (at most 200 lines a day without any kind of burst).

**Comment by k4nar** [comment]
@b4stien : Any news on that? If this is really a bug in Circus, I'm surprised that we don't get other reports.

**Comment by b4stien** [comment]
Hey, no news since I've switched 90% of my processes to Supervisor after this very specific issue...

I guess you can close, it's been a long time and there has been some changes to Circus in the meantime, maybe it doesn't hang anymore.

**Comment by k4nar** [comment]
Ok thanks :) .
