### ISSUE TITLE
'circusctl stop' does not release log file handles

### ISSUE THREAD

**Issue by bengecko** [circus-tent/circus#884]
When running circusd around a linux process, everything works with logging, options, etc. except when stopping the process using 'circusctl stop' the log file handle is still left open. I had to quit circusd altogether to let the filehandle go.

**Comment by k4nar** [comment]
Indeed, after a quick look a the code when a watcher stops it doesn't close its `stdout_stream` and `stderr_stream`.

@scottkmaxwell: You introduced the closing of the streams in the Watcher in this commit: https://github.com/circus-tent/circus/commit/c12c634aa3bbce0a9fb2ccf2a3a6ed7b5b1ff62c. Any reasion why `Watcher.stop` doesn't call `Watcher._stop` with `close_output_streams=True` ?

**Comment by scottkmaxwell** [comment]
Good idea. I made the original change to support the papa kernel and tried to change as little as possible, but releasing the handles on watcher.stop and on abort triggered by the after_start hook seems like the right thing to do. Fixed in #885. Please give it a try.

**Comment by bengecko** [comment]
Thanks you guys! We'll check it out as soon as we get the cycles

**Comment by k4nar** [comment]
@bengecko : Did you have the occasion to test the PR?

**Comment by k4nar** [comment]
I'm closing this as it seems to have been fixed.
