### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by josegonzalez** [circus-tent/circus#889]
Would be nice to get any enhancements etc. out in a "stable" release. Is there a roadmap somewhere where we might be able to see what blockers are around for cutting a release?

**Comment by k4nar** [comment]
There isn't any roadmap. However, the only blocker I see is #872. It's not really an issue a it's just some tests failing because they were not actually called with Tornado < 4.0. But still, it would be nice to see them fixed before a new release.

**Comment by matleh** [comment]
+1
I, too, would very much appreciate a new release.
Thanks for the great work.

**Comment by k4nar** [comment]
I would like #898 to be fixed. It only affects the tests (AFAIK) but it would be great if those were stable for the new release.

**Comment by k4nar** [comment]
0.12 has been released :) .
