### ISSUE TITLE
More python 3.4 issues

### ISSUE THREAD

**Issue by abadger1406** [circus-tent/circus#895]
import urlparse
ImportError: No module named 'urlparse'

Think this has changed name in python 3.4

'%s"\nInitial error: %s' % (reqs, str(e)))
ImportError: You need to install dependencies to run the webui. You can do so by using "pip install -r /home/dave/ap/lib/python3.4/site-packages/circusweb/web-requirements.txt"
Initial error: No module named 'urlparse'

But the file /home/dave/ap/lib/python3.4/site-packages/circusweb/web-requirements.txt does not exist, and I cannot find it in my git clone....

must be doing something wrong in trying to get this running with python 3.4 ...

**Comment by k4nar** [comment]
As for #894, this is an issue with circus-web. Please test with circus-web master and report the errors there.
