### ISSUE TITLE
Use API to manage processes dynamically

### ISSUE THREAD

**Issue by owais** [circus-tent/circus#904]
Is it possible to manage processes dynamically through an API (or CLI or ZMQ) instead of defining in the config file?

I'm imagining an API like this,

```python
process = circus.spawn_and_manage('/path/to/bin', {'--someParameter': 'someValue'})
```

This manages the process as if it was found in the config file. I can use the API to get status of the process or remove it.

```python
circus.kill_and_remove(process)
```

**Comment by matleh** [comment]
You can achieve that with the `add` command. See https://circus.readthedocs.org/en/0.11.1/for-ops/commands/add/

**Comment by owais** [comment]
Perfect. Thanks!

**Comment by k4nar** [comment]
Indeed, the simpler is to use Circusctl for that. If you need a more pythonic way, you can use [CircusClient](https://github.com/circus-tent/circus/blob/master/circus/client.py#L86) (we need doc !).

**Comment by k4nar** [comment]
Waiting for some proper documentation, here is an example on how to use Circus as a library: https://gist.github.com/k4nar/25dddf2cd6f1590d257d
