### ISSUE TITLE
circusctl reload vs restart for continuous deployment?

### ISSUE THREAD

**Issue by AdrianLC** [circus-tent/circus#906]
Hello,

I have been trying to understand the difference between this two commands.

The man does not say much:
```
reload: Reload the arbiter or a watcher
restart: Restart the arbiter or a watcher
```
(and then there's some info about the signals under `reload`)

I see in the code that `reload` calls `restart` internally, so I assume that it's a restart with some additional steps.

Could someone explain, please? I would be interested in knowing which of the two should I be calling to restart our worker processes (celery) gracefully. We are having serious trouble with the old processes never stopping and always assumed it to be a bug on celery... but we recently changed the stop signal to KILL and even that will not kill them.

Also, we have a buildbot restarting the whole circusd instance with ansible. This should restart all the watchers, right?

I tried to avoid creating an issue for questions, but could not find answers anywhere else. Sorry :(

Thank you,
Adrián

**Comment by k4nar** [comment]
As I understand it, `restart` will stop then start again your process, whereas `reload` will do the same thing but *also* reload the configuration.

**Comment by scottkmaxwell** [comment]
Restart is stop, followed by start. The process is guaranteed to be completely down, then restarted, so you will have an interruption in service. Reload may be the same, but it tries to be more polite. It can simply issue a HUP to each process to tell them to reload internally. It can also do a series of processes sequentially so that everything is not down at once. I wrote a reload hook for uWSGI that will start up a new copy of your web server, then shut down the old processes. This results in a no-downtime restart.

From the comment in reload.py:

        Reload the arbiter or a watcher
        ===============================

        This command reloads all the process in a watcher or all watchers. This
        will happen in one of 3 ways:

        * If graceful is false, a simple restart occurs.
        * If `send_hup` is true for the watcher, a HUP signal is sent to each
          process.
        * Otherwise:
            * If sequential is false, the arbiter will attempt to spawn
              `numprocesses` new processes. If the new processes are spawned
              successfully, the result is that all of the old processes are
              stopped, since by default the oldest processes are stopped when
              the actual number of processes for a watcher is greater than
              `numprocesses`.
            * If sequential is true, the arbiter will restart each process
              in a sequential way (with a `warmup_delay` pause between each
              step)


        ZMQ Message
        -----------

        ::

            {
                "command": "reload",
                "properties": {
                    "name": '<name>",
                    "graceful": true,
                    "sequential": false,
                    "waiting": False
                }
            }

        The response return the status "ok". If the property graceful is
        set to true the processes will be exited gracefully.

        If the property name is present, then the reload will be applied
        to the watcher.


        Command line
        ------------

        ::

            $ circusctl reload [<name>] [--terminate] [--waiting]
                                        [--sequential]

        Options
        +++++++

        - <name>: name of the watcher
        - --terminate; quit the node immediately

**Comment by AdrianLC** [comment]
Turns out celery expects SIGKILL for the cold shut down.
https://github.com/celery/celery/blob/v3.1.18/celery/apps/worker.py#L300

 Solved with a before_signal hook:
```python
def SIGQUIT(arbiter, hook_name, watcher, pid, signum, **kwargs):
    if signum == signal.SIGKILL:
        logger.debug("running SIGQUIT hook for %s", watcher.name)
        watcher.send_signal(pid, signal.SIGQUIT)
        watcher.reap_process(pid)
    return True
```
