### ISSUE TITLE
How to start a watcher for a graphical (X11) program?

### ISSUE THREAD

**Issue by ViktorNova** [circus-tent/circus#914]
I'm having a hard time getting Circus to start and monitor a program that runs inside X.. I am new to Circus but it is dead simple and I have no problem getting it to run scripts and whatnot, just when I try to run anything graphical, it does not work. The logfile is created but remains 0 bytes, so I am unsure how to debug it

Here's my config for the watcher in question
````
[watcher:dmx]
cmd = "qlcplus --operate --open /home/stagecraft/SYSTEM/GLOBAL/The Secret Light.qxw"
# shell = True
stdout_stream.class = FileStream
stdout_stream.filename = dmx.log

````
(*have also tried with "shell = True" with no difference) Circusd is run as the current user loged into X,

What am I missing here?

**Comment by Natim** [comment]
Did you try to define the ``DISPLAY=:0.0`` environment variable.

**Comment by k4nar** [comment]
You should add `copy_env=True` to your watcher.

**Comment by Natim** [comment]
:+1: That would work as well.

**Comment by ViktorNova** [comment]
That was fast! Both options worked great (with ````copy_env=True```` giving less weird results), thanks guys!
