### ISSUE TITLE
Feature request: consider adding `stop_cmd` and `stop_args` to `Watcher` as alternative `stop_signal`

### ISSUE THREAD

**Issue by posita** [circus-tent/circus#917]
Some things do not behave well with signals and much prefer to be told (e.g., by external commands) that it's time to shut down gracefully. Rather than write signal-handling wrappers, it might be nice to allow watchers to exec `[stop_cmd] [stop_args]` in lieu of sending `stop_signal`. It might be considered an error to specify both `stop_cmd` and `stop_signal`. `stop_children` would be meaningless for `stop_cmd`. `graceful_timeout` could work with `stop_cmd` in that `SIGKILL` could be sent if the process has still not halted on its own after calling `stop_cmd`.

**Comment by k4nar** [comment]
This should be handled by a `before_signal` hook.

It would be great to have an example in the docs though :) .

**Comment by k4nar** [comment]
I'm closing this as we already have a solution for that. If anyone want to add an example in the doc I would be happy to merge it.

**Comment by posita** [comment]
@k4nar, perhaps I wasn't clear with the original request, but I don't think `before_signal` satisfies the intention. While one certainly _could_ write a `before_signal` hook that creates a subprocess, this is far from admin-friendly. One has to know Python _and_ understand signal processing _and_ understand the potential pitfalls associated with subprocesses. Plus, I can't see an obvious way to fall back to a signal handler in the event that the command fails to halt the process without requiring a _lot_ of code to be written by the admin. My suggestion was to expose such a mechanism via the `.ini` file.

**Comment by k4nar** [comment]
Okay thanks, I understand.

However, Circus is using signals extensively, and I don't really know if we could replace them easily. Another solution would be to write a wrapper for the app with the right sighandlers.

**Comment by posita** [comment]
> Another solution would be to write a wrapper for the app with the right sighandlers.

This kind of signal-catching glue-layer is exactly what I've done in the past, but it's a _lot_ of work from an admin perspective, and probably common enough to consider exposing a generic solution. That was all I intended with this feature request.

**Comment by k4nar** [comment]
I'm sorry but I really don't see how Circus could fix that. Signals are at the core of Circus (graceful timeouts, restarting, sendsignal and kill commands, etc…), I'm not sure that we can (or should) allow to replace them by commands.
