### ISSUE TITLE
Feature request: consider adding `disable = (true|false)` to watcher configuration

### ISSUE THREAD

**Issue by posita** [circus-tent/circus#918]
It might be nice to be able to disable a watcher without commenting out its entire configuration or renaming/moving its file (if it was included). Perhaps a watcher could support a `disable` configuration directive, where, if true, that watcher would be ignored. (Defaults to `false` where omitted, if that wasn't obvious.)

**Comment by k4nar** [comment]
I think that this is the kind of feature which would add a lot of complexity to the Watcher. However I think we would accept a PR if it turns out to be simple.

**Comment by k4nar** [comment]
Actually there is already the `autostart` option for that.
