### ISSUE TITLE
When circusd is started from an SSH connection, PID file is lost on disconnect

### ISSUE THREAD

**Issue by cjhenck** [circus-tent/circus#919]
I often restart my circus server via SSH, and when I do so, the PID file is lost.  I will probably create an appropriate script for the init services, but it seems like this is nevertheless an undesirable behavior.

**Comment by k4nar** [comment]
I don't understand what it is an undesirable behavior, could you be more specific?

**Comment by cjhenck** [comment]
I run a script via SSH that calls this command:
```bash
sudo -H -u www-data circusd --daemon circus.ini
```
which successfully starts circusd and creates a PID file: /tmp/circusd.pid

When I exit the SSH session and reconnect, the PID file is gone, though circusd is still running.

**Comment by k4nar** [comment]
I don't understand why that would happen, we create the pidfile after daemonizing, and we only delete it after the arbiter is stopped. I'll try to reproduce though.

**Comment by k4nar** [comment]
@cjhenck : I tried to reproduce, but actually cirusd is killed as soon as I quit my ssh session. This makes sense because we are only forking once with the `--daemon` option. Are you sure that in your scenario circusd is still running?

**Comment by cjhenck** [comment]
It definitely seemed that way at the time.  Unfortunately I can't remember how we resolved it, so I'll just close the issue.
