### ISSUE TITLE
multi circus.ini files 

### ISSUE THREAD

**Issue by Alwerdani** [circus-tent/circus#926]
hi , 
i am trying to run two django apps with circus on same droplet at digitalocean 
every app is work alone verygood with seprated circus.ini files but the problem come when make the two apps in same file like this:

**circus.ini**
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
statsd = true

[watcher:app1]
working_dir = /home/user1/projects/app1

cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 app1.wsgi
uid = user1
copy_env = true
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/user1/projects/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4

[env:app1]
PATH = /home/user1/.virtualenvs/app1/bin:$PATH
TERM=rxvt-256color
SHELL=/bin/bash
USER=user1
LANG=en_US.UTF-8
HOME=/home/user1
PYTHONPATH=/home/user1/.virtualenvs/app1/lib/python3.4/site-packages

[watcher:app2]
working_dir = /homeuser2/projects/app2

cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8002 app2.wsgi
uid = user2
copy_env = true
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/user2/projects/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4

[env:app2]
PATH = /home/user2/.virtualenvs/app2/bin:$PATH
TERM=rxvt-256color
SHELL=/bin/bash
USER=user2
LANG=en_US.UTF-8
HOME=/home/user2
PYTHONPATH=/home/user2/.virtualenvs/app2/lib/python3.4/site-packages

but not work 

and trying to make two conf files like this 
app1.conf:
start on filesystem and net-device-up IFACE=lo
stop on runlevel [016]

respawn
exec /usr/local/bin/circusd /home/user1/projects/circus.ini

**app1.conf:** 
start on filesystem and net-device-up IFACE=lo
stop on runlevel [016]

respawn
exec /usr/local/bin/circusd /home/user1/projects/circus.ini

**app2.conf:** 
start on filesystem and net-device-up IFACE=lo
stop on runlevel [016]

respawn
exec /usr/local/bin/circusd /home/user1/projects/circus.ini
but still not work 

any other suggestions ?

**Comment by cgarciaarano** [comment]
Are you trying to run 2 instances of circus? 

I haven't tried this kind of setup, but I think you must use different `circus.ini` files. Be sure to change the `[circus]` section so the `endpoint` and `pubsub_endpoint ` are different.

Something like these:

**circus1.ini**
```ini
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
statsd = true

[watcher:app1]
working_dir = /home/user1/projects/app1

cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 app1.wsgi
uid = user1
copy_env = true
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/user1/projects/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4

[env:app1]
PATH = /home/user1/.virtualenvs/app1/bin:$PATH
TERM=rxvt-256color
SHELL=/bin/bash
USER=user1
LANG=en_US.UTF-8
HOME=/home/user1
PYTHONPATH=/home/user1/.virtualenvs/app1/lib/python3.4/site-packages
```

**circus2.ini**
```ini
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5557
pubsub_endpoint = tcp://127.0.0.1:5558
statsd = true

[watcher:app2]
working_dir = /homeuser2/projects/app2

cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8002 app2.wsgi
uid = user2
copy_env = true
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/user2/projects/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4

[env:app2]
PATH = /home/user2/.virtualenvs/app2/bin:$PATH
TERM=rxvt-256color
SHELL=/bin/bash
USER=user2
LANG=en_US.UTF-8
HOME=/home/user2
PYTHONPATH=/home/user2/.virtualenvs/app2/lib/python3.4/site-packages
```

And your init scripts:

**app1.conf**
```
start on filesystem and net-device-up IFACE=lo
stop on runlevel [016]

respawn
exec /usr/local/bin/circusd /home/user1/projects/circus1.ini
```

**app2.conf**
```
start on filesystem and net-device-up IFACE=lo
stop on runlevel [016]

respawn
exec /usr/local/bin/circusd /home/user1/projects/circus2.ini
```

**Comment by Alwerdani** [comment]
Thank you , it work :)
 my problem was in endpoint and pubsub_endpoint

**Comment by cgarciaarano** [comment]
You're welcome

Anyway, ¿why are you running 2 circus instances instead of one single circus? You can run and manage multiple watchers in one single circus, and running multiple circus seems inefficient.

In case you need to reload circus frequently (changes in your ini config file), you can use [papa] (https://circus.readthedocs.org/en/latest/for-ops/papa/>), which is a recent feature in circus 0.12. I'm still testing it, but looks promising!

Regards

**Comment by k4nar** [comment]
I'm closing this as it has been solved :) .

**Comment by jlariza** [comment]
Hi!

I am trying to use that configuration to run two circus instances at once, but I keep getting `exception Address already in use caught`.

What am I missing?

Thank you,
