### ISSUE TITLE
More problems with watchers when mixing upper and lower cases

### ISSUE THREAD

**Issue by StefanWiechula** [circus-tent/circus#936]
#927 fixed the `restart` command but similar issues exist with other commands.

See comment here: https://github.com/circus-tent/circus/issues/927#issuecomment-151531715

**Comment by k4nar** [comment]
The solution to that seems to make sure that we cannot create two watchers with the same lowercase name (like `Foo` & `foo`). This is a bit of a edge case though in my opinion.
