### ISSUE TITLE
Circus changes is not persist

### ISSUE THREAD

**Issue by natsu90** [circus-tent/circus#937]
Hey guys, I'm adding new watcher from CLI, all works well. But after did server restart, the added watcher is not running and seems no longer exist in list. How do I add watcher and remain persist after server restart, besides editing the `ini` file? Because I need the watcher can be add and remove on the fly. Thanks.

**Comment by k4nar** [comment]
The `.ini` file is the only source of information when starting circus, and circus cannot edit it.
I don't think that circus will ever provide an option for saving the current watchers in a file.
