### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ismail-s** [circus-tent/circus#941]
I am trying to use Circus to manage my [Pyramid app](www.github.com/ismail-s/fireblog). However, I am having trouble configuring logging-it seems like the loglevel and logoutput settings only work for some of the log messages and not others. For instance, all the log messages my app makes get sent straight to STDOUT, and don't seem subject to control from `circus.ini`.

1. How do I do control the logging of my application
1. Where is information on configuring the `circus.ini` file? I've been looking around and I can't find a page that says:
  1. What config options are available for each section
  1. What each option does

**Comment by ismail-s** [comment]
Ok, I have managed to get my web app to send log messages to the same file as Circus is, by specifying in my Paste file for my web app to use a FileHandler. However, log messages about requests being processed is still being printed to STDOUT for some reason.

**Comment by k4nar** [comment]
@ismail-s : I'm sorry we never answered you :( . I'm closing this as it's quite old, please re-open if you still have an issue with that.

**Comment by ismail-s** [comment]
@k4nar No problem, I moved on and used uwsgi instead for my pyramid app.

**Comment by ismail-s** [comment]
@k4nar Although, after browsing through the documentation, it looks like logging is now documented, along with the ini file format. So it makes sense that this issue is now closed.
