### ISSUE TITLE
Some issues with watchdog

### ISSUE THREAD

**Issue by kyudin** [circus-tent/circus#945]
There are few issues, that prevent to use watchdog:
1) max_count variable, readed from config should be casted to integer.
2) bytes are received from udp socket, but regex is string, so, re.match will throw exception and since bytes are received from socket and regex - hearthbeat['pid'] should be decoded too.
3) watcdog kills himself.
[watchdog.txt](https://github.com/circus-tent/circus/files/59482/watchdog.txt)

**Comment by k4nar** [comment]
I'm sorry but I'm closing this issue. Please open an issue for each point, with a bit more information.
