### ISSUE TITLE
PyPI Release?

### ISSUE THREAD

**Issue by mrasband** [circus-tent/circus#954]
With some of the known issues with python 3.5 compatibility being fixed (namely #939), it would be fantastic if you could cut a new release and publish it to PyPI.  Python 3.5 was released in Sept and the latest circus release is from August.  Thanks!

For now we are able to use the current commit in edit mode to ensure freeze can get it:

`pip install -e git+https://github.com/circus-tent/circus.git@9b8a1a5cb641a7b910fec2c7a4fb0f637538841a#egg=circus-master`

**Comment by k4nar** [comment]
Indeed, I'll make a new minor release. Thanks!

**Comment by k4nar** [comment]
@mrasband : Circus 0.13 is released, thanks for the heads-up!

**Comment by mrasband** [comment]
@k4nar Thank you!
