### ISSUE TITLE
How can i use circus with nodejs

### ISSUE THREAD

**Issue by Alwerdani** [circus-tent/circus#958]
Hello,
currently, I am using circus Django project beside nodejs simple app to add some functionality to the django project.
 so, is there any way to manage the two project in the same circus.ini file?

**Comment by k4nar** [comment]
Well yes, you simply need to define two watchers, one for Django's server, and one for your node server.

**Comment by Alwerdani** [comment]
thanks for your replay :)

I know that i can define two watchers,  my problem in envs  what is the cmd i needed to nodejs , is you can give me an example for this envs i will  be thankful for you

**Comment by Natim** [comment]
Here is an example I've made for Node worker: https://github.com/mozilla-services/loop-server/blob/master/circus/loop-server.ini

**Comment by Natim** [comment]
Hope it helps.

**Comment by k4nar** [comment]
I'm closing this as it has been answered.
