### ISSUE TITLE
How to format Watcher's workers log messages

### ISSUE THREAD

**Issue by ayashjorden** [circus-tent/circus#961]
Hi,
If a Watcher runs multiple workers, funnelling their logs to the same file(s), how can I format the log messages to contain at least PID and timestamp?

Thank you,
Yarden

**Comment by k4nar** [comment]
I'm pretty sure you can do that using the `loggerconfig` option. Cf the end of this section: http://circus.readthedocs.io/en/latest/for-ops/configuration/#circus-single-section

We could use more documentation on that though.

**Comment by ayashjorden** [comment]
Thank you @k4nar
