### ISSUE TITLE
Unittests hanging with get_arbiter

### ISSUE THREAD

**Issue by badisa** [circus-tent/circus#964]
Trying to use Circus to start up server and client processes for unit testing, but while it works in python 2.7, when using 3.4 it hangs at the end of the tests. I am using Pytest as my test runner, but even using the unittest module it hangs. Used [this](https://circus.readthedocs.org/en/latest/for-devs/#using-circus-as-a-library) as documentation to do this.

```
arbiter = get_arbiter([], debug=True, background=True)


def setUpModule():
    arbiter.add_watcher(
        "TestServer",
        "python server_script.py",
        copy_env=True,
        respawn=False
    )
    arbiter.start()


def tearDownModule():
    watcher = arbiter.get_watcher("TestServer")
    watcher.kill_processes()
    watcher.stop()
    arbiter.stop()
```

Unsure if I am using Circus correctly here as I am having to add a watcher to the arbiter to make sure the environment variables get copied. 

When I did a trace of where it was hanging it looks like it was caused by `controller.py` which repeatedly tried to call `self.loop.add_future()`. It appears to run all of my `tearDownModule()` function besides the `arbiter.stop()`

```
controller.py(101):             self.loop.add_future(self._managing_watchers_future,
controller.py(102):                                  self._manage_watchers_cb)
```

**Comment by k4nar** [comment]
@badisa : It's a bug with ZMQ & Python 3.4 (https://github.com/zeromq/pyzmq/pull/513), you have to close the context manually.

```
import zmq

zmq.Context.instance().destroy()
```
