### ISSUE TITLE
Using Circus to run tests

### ISSUE THREAD

**Issue by prokher** [circus-tent/circus#966]
Dear maintainers,

I am using Circus to run my Django web application and required services, namely Celery and Redis. For e2e tests I also need to run these services. I thought, that I can use Circus to run such tests? It already starts all the services my app needs. So I wrote separate config "test.ini" which runs `python manage.py test` instead of regular `python manage.py runserver`. I also used `respawn = False` to avoid restarting of tests. Unfortunately Circus continues running even when tests finish. I understand why - Circus designed to watch and restart processes. So my question is the following. Is there a possibility to stop Circus when one selected watched process ends? It could be very useful for testing purposes I suppose.

**Comment by prokher** [comment]
Eventually, I've used hooks to be notified when testing process ends. Bu how can I correctly shutdown circus from inside hook body? I tried `arbiter.stop` but it raises `circus.exc.ConflictError` exception:

```
2016-03-11 16:46:50 circus[30232] [ERROR] Hook 'after_stop' failed
Traceback (most recent call last):
  File "/home/prokher/Dev/VirtEnvsPy/pSeven/lib/python3.5/site-packages/circus/watcher.py", line 903, in call_hook
    result = self.hooks[hook_name](**hook_kwargs)
  File "/home/prokher/Dev/Lab/pSeven/settings/test.py", line 22, in super_hook
    arbiter.stop(42)
  File "/home/prokher/Dev/VirtEnvsPy/pSeven/lib/python3.5/site-packages/circus/util.py", line 1020, in wrapper
    % arbiter._exclusive_running_command)
circus.exc.ConflictError: arbiter is already running manage_watchers command
```

so is it possible to correctly shutdown Circus from the hook?

**Comment by prokher** [comment]
At last, to shutdown Circus I used `arbiter._stop(True)`, it seems to work, but I am not sure it is correct.

**Comment by k4nar** [comment]
I'm not sure what's the best way to do that. `arbiter._stop(True)` should work but is a bit brutal.

This conflict thing is pretty annoying, but I don't know how to avoid that in Circus. A solution would be to try `arbiter.stop()`, and wait a few milliseconds if you get a `ConflictError`.

I'm closing this issue as you seem to have solved your issue though.
