### ISSUE TITLE
NOT AN ISSUE: But a BIG THANK YOU!

### ISSUE THREAD

**Issue by aventurella** [circus-tent/circus#972]
Hey, I just wanted to say thank you to everyone who has worked on this project. I ran into an issue with something else and then I recalled that Circus is developer friendly to be included inside other applications and lo! happiness.

Anyway, I looked on IRC but it's dead in that channel, I just wanted to give a big thanks to everyone who worked on this. 

I don't think people say thank you enough in OSS.

Anyway, thanks again to all who contributed, you made my day easier!

**Comment by tarekziade** [comment]
Thanks! that's really nice of you!  cc @k4nar

**Comment by k4nar** [comment]
Thank you very much @aventurella! Even though things have been moving pretty slowly lately, will try to keep making Circus awesome :) .

**Comment by k4nar** [comment]
Thank you again @aventurella for your kind words :) .

I'm closing it as I think every active contributor to Circus saw that and I want to clean up our issues.
