### ISSUE TITLE
0.14.0 release?

### ISSUE THREAD

**Issue by billygout** [circus-tent/circus#991]
Hi @k4nar, I'd like to know whether you have plans to make a 0.14.0 release. Thanks!

**Comment by cmorgan** [comment]
+1
are most folks running an official release or github:master?

**Comment by k4nar** [comment]
I don't see any blocking point for a 0.14 now, so yes I'll try to release it soon :) .

**Comment by ldav1s** [comment]
I'm running an official release.  I would like to see at least [969](https://github.com/circus-tent/circus/pull/969) fixed there.

**Comment by k4nar** [comment]
I just released [Circus 0.14](https://github.com/circus-tent/circus/releases/tag/0.14.0).

Sorry for the (very) long delay and thanks to the contributors :) .
