### ISSUE TITLE
run curcis with curcis.ini error tornadio2

### ISSUE THREAD

**Issue by thanhngvpt** [circus-tent/circus#993]
Hi Author.
When i run circusd curcis.ini (from here http://circus.readthedocs.io/en/latest/tutorial/step-by-step/#examples) alway occur error 

https://dpaste.de/qrim

Please help me how to resolve

**Comment by k4nar** [comment]
Hi, this looks like you're trying to use a Python 2 dependency (`tornadio2`) with Python 3.5. I don't think it has anything to do with Circus.

**Comment by thanhngvpt** [comment]
@k4nar it right, i just create a virtualenv base on python2 and it work well. many thanks to your answer.

**Comment by k4nar** [comment]
Great :) .
